#!/bin/sh

GOPATH=/web/godoc export GOPATH

github_path=`printf %s "$REPO_URL" | sed 's;https\?://;;'`
import_path=`grep "$github_path" /etc/gogive.conf | awk '{print $1}'`

if [ -z "$import_path" ]
then
	printf "Skipping repository %s, not in gogive.conf\n" "$github_path"
	exit
fi

printf "Found canonical path '%s' for '%s'\n" "$import_path" "$github_path"

printf "Fetching aqwari.net%s\n" "$import_path"
docroot="/web/godoc/src/pkg${import_path}"
if [ -d "${docroot}/.git" ]
then
	cd "$docroot"
	git pull origin master
else
	mkdir -p "$docroot"
	cd "$docroot"
	git clone "$REPO_URL" .
fi

